#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum ChunkKind {
	Add,
	After,
	Alias,
	Algo,
	Arg,
	Argv,
	Array,
	At,
	Attr,
	AttrExpr,
	Attrs,
	Block,
	BlockIf,
	BlockLocals,
	Body,
	Case,
	Cases,
	Catch,
	Cell,
	Class,
	Clause,
	Cmd,
	Code,
	Cond,
	Constructor,
	Contract,
	Copy,
	Custom,
	Declarations,
	Decl,
	DefaultExport,
	Define,
	Directive,
	Either,
	Elif,
	Else,
	Enum,
	Env,
	Error,
	Except,
	Exports,
	Expose,
	Expression,
	Field,
	Fields,
	File,
	Frame,
	Function,
	For,
	ForIn,
	ForOf,
	Form,
	Frontmatter,
	Group,
	GroupBy,
	Headers,
	Healthcheck,
	Html,
	Hunks,
	Hunk,
	If,
	Iface,
	Impl,
	Imports,
	Includes,
	InlineFragment,
	Install,
	Interface,
	Interpolation,
	Item,
	Join,
	Key,
	KeyScripts,
	Label,
	Let,
	List,
	Loop,
	Macro,
	Map,
	Markdown,
	Match,
	Method,
	Methods,
	Module,
	Mustache,
	Object,
	Operation,
	Operator,
	Option,
	Options,
	OrderBy,
	Parameters,
	Preamble,
	Proc,
	Process,
	Project,
	Proto,
	Py,
	Python,
	Query,
	Receive,
	Recipe,
	Relations,
	Render,
	Return,
	Root,
	Rule,
	Schema,
	Script,
	ScriptModule,
	ScriptSetup,
	Section,
	Select,
	Setting,
	Shebang,
	Shell,
	Slot,
	Snippet,
	Source,
	Stage,
	StaticInit,
	Statements,
	Struct,
	Style,
	StyleScoped,
	Switch,
	Table,
	Tag,
	Target,
	Template,
	Text,
	Trait,
	Translation,
	Try,
	Ts,
	Type,
	Typescript,
	Union,
	User,
	Val,
	Variable,
	Variant,
	Variants,
	VersionGate,
	When,
	Where,
	While,
	With,
	Workdir,
	Conflict,
	Ours,
	Theirs,
	Chunk,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum SummaryStyle {
	Function,
	Variable,
	Imports,
	Default,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ChunkTraits {
	pub groupable:                bool,
	pub packed:                   bool,
	pub addressable_leaf:         bool,
	pub always_preserve_children: bool,
	pub has_addressable_members:  bool,
	pub summary:                  SummaryStyle,
	pub container:                bool,
}

const DEFAULT_TRAITS: ChunkTraits = ChunkTraits {
	groupable:                false,
	packed:                   false,
	addressable_leaf:         false,
	always_preserve_children: false,
	has_addressable_members:  false,
	summary:                  SummaryStyle::Default,
	container:                false,
};

const GROUP_TRAITS: ChunkTraits = ChunkTraits { groupable: true, ..DEFAULT_TRAITS };

const CONTAINER_TRAITS: ChunkTraits = ChunkTraits { container: true, ..DEFAULT_TRAITS };

const ADDRESSABLE_CONTAINER_TRAITS: ChunkTraits =
	ChunkTraits { container: true, has_addressable_members: true, ..DEFAULT_TRAITS };

const PRESERVE_CHILDREN_TRAITS: ChunkTraits =
	ChunkTraits { container: true, always_preserve_children: true, ..DEFAULT_TRAITS };

const PACKED_LEAF_TRAITS: ChunkTraits =
	ChunkTraits { packed: true, addressable_leaf: true, ..DEFAULT_TRAITS };

const FUNCTION_TRAITS: ChunkTraits =
	ChunkTraits { summary: SummaryStyle::Function, ..DEFAULT_TRAITS };

const VARIABLE_TRAITS: ChunkTraits = ChunkTraits {
	packed: true,
	addressable_leaf: true,
	summary: SummaryStyle::Variable,
	..DEFAULT_TRAITS
};

const IMPORTS_TRAITS: ChunkTraits =
	ChunkTraits { groupable: true, summary: SummaryStyle::Imports, ..DEFAULT_TRAITS };

impl ChunkKind {
	pub const fn prefix(self) -> &'static str {
		match self {
			Self::Add => "add",
			Self::After => "aft",
			Self::Alias => "al",
			Self::Algo => "algo",
			Self::Arg => "arg",
			Self::Argv => "argv",
			Self::Array => "ar",
			Self::At => "at",
			Self::Attr => "attr",
			Self::AttrExpr => "aex",
			Self::Attrs => "ats",
			Self::Block => "blk",
			Self::BlockIf => "bif",
			Self::BlockLocals => "blc",
			Self::Body => "b",
			Self::Case => "case",
			Self::Cases => "cs",
			Self::Catch => "ctc",
			Self::Cell => "cell",
			Self::Class => "cls",
			Self::Clause => "cla",
			Self::Cmd => "cmd",
			Self::Code => "code",
			Self::Cond => "cond",
			Self::Constructor => "ctor",
			Self::Contract => "ctr",
			Self::Copy => "copy",
			Self::Custom => "cus",
			Self::Declarations => "d",
			Self::Decl => "decl",
			Self::DefaultExport => "dex",
			Self::Define => "def",
			Self::Directive => "dir",
			Self::Either => "eth",
			Self::Elif => "elif",
			Self::Else => "else",
			Self::Enum => "en",
			Self::Env => "env",
			Self::Error => "err",
			Self::Except => "exc",
			Self::Exports => "exp",
			Self::Expose => "exo",
			Self::Expression => "ex",
			Self::Field => "fld",
			Self::Fields => "flds",
			Self::File => "file",
			Self::Frame => "fr",
			Self::Function => "fn",
			Self::For => "for",
			Self::ForIn => "fri",
			Self::ForOf => "fro",
			Self::Form => "form",
			Self::Frontmatter => "fm",
			Self::Group => "grp",
			Self::GroupBy => "gby",
			Self::Headers => "hdrs",
			Self::Healthcheck => "hck",
			Self::Html => "html",
			Self::Hunks => "hks",
			Self::Hunk => "hunk",
			Self::If => "if",
			Self::Iface => "ifc",
			Self::Impl => "ipl",
			Self::Imports => "imp",
			Self::Includes => "incl",
			Self::InlineFragment => "ifr",
			Self::Install => "inst",
			Self::Interface => "intf",
			Self::Interpolation => "itp",
			Self::Item => "item",
			Self::Join => "join",
			Self::Key => "key",
			Self::KeyScripts => "ksc",
			Self::Label => "lbl",
			Self::Let => "let",
			Self::List => "list",
			Self::Loop => "loop",
			Self::Macro => "mc",
			Self::Map => "map",
			Self::Markdown => "md",
			Self::Match => "mt",
			Self::Method => "m",
			Self::Methods => "ms",
			Self::Module => "mod",
			Self::Mustache => "mst",
			Self::Object => "obj",
			Self::Operation => "op",
			Self::Operator => "oper",
			Self::Option => "opt",
			Self::Options => "opts",
			Self::OrderBy => "oby",
			Self::Parameters => "p",
			Self::Preamble => "pre",
			Self::Proc => "proc",
			Self::Process => "prcs",
			Self::Project => "proj",
			Self::Proto => "pt",
			Self::Py => "py",
			Self::Python => "pyt",
			Self::Query => "qry",
			Self::Receive => "recv",
			Self::Recipe => "rcp",
			Self::Relations => "rels",
			Self::Render => "rnd",
			Self::Return => "ret",
			Self::Root => "root",
			Self::Rule => "rule",
			Self::Schema => "sch",
			Self::Script => "scr",
			Self::ScriptModule => "smo",
			Self::ScriptSetup => "sse",
			Self::Section => "sct",
			Self::Select => "sel",
			Self::Setting => "stn",
			Self::Shebang => "shb",
			Self::Shell => "sh",
			Self::Slot => "slot",
			Self::Snippet => "snip",
			Self::Source => "src",
			Self::Stage => "stg",
			Self::StaticInit => "sni",
			Self::Statements => "st",
			Self::Struct => "stc",
			Self::Style => "sty",
			Self::StyleScoped => "sco",
			Self::Switch => "sw",
			Self::Table => "tbl",
			Self::Tag => "tag",
			Self::Target => "tgt",
			Self::Template => "tmpl",
			Self::Text => "text",
			Self::Trait => "tr",
			Self::Translation => "trs",
			Self::Try => "try",
			Self::Ts => "ts",
			Self::Type => "ty",
			Self::Typescript => "tysc",
			Self::Union => "u",
			Self::User => "user",
			Self::Val => "val",
			Self::Variable => "var",
			Self::Variant => "vr",
			Self::Variants => "vrs",
			Self::VersionGate => "vg",
			Self::When => "when",
			Self::Where => "wh",
			Self::While => "wl",
			Self::With => "with",
			Self::Workdir => "wd",
			Self::Conflict => "cfl",
			Self::Ours => "ours",
			Self::Theirs => "ths",
			Self::Chunk => "ch",
		}
	}

	pub const fn traits(self) -> &'static ChunkTraits {
		match self {
			Self::Add => &GROUP_TRAITS,
			Self::After => &GROUP_TRAITS,
			Self::Alias => &DEFAULT_TRAITS,
			Self::Algo => &CONTAINER_TRAITS,
			Self::Arg => &DEFAULT_TRAITS,
			Self::Argv => &DEFAULT_TRAITS,
			Self::Array => &DEFAULT_TRAITS,
			Self::At => &DEFAULT_TRAITS,
			Self::Attr => &DEFAULT_TRAITS,
			Self::AttrExpr => &DEFAULT_TRAITS,
			Self::Attrs => &CONTAINER_TRAITS,
			Self::Block => &DEFAULT_TRAITS,
			Self::BlockIf => &DEFAULT_TRAITS,
			Self::BlockLocals => &DEFAULT_TRAITS,
			Self::Body => &DEFAULT_TRAITS,
			Self::Case => &DEFAULT_TRAITS,
			Self::Cases => &GROUP_TRAITS,
			Self::Catch => &DEFAULT_TRAITS,
			Self::Cell => &CONTAINER_TRAITS,
			Self::Class => &CONTAINER_TRAITS,
			Self::Clause => &DEFAULT_TRAITS,
			Self::Cmd => &GROUP_TRAITS,
			Self::Code => &GROUP_TRAITS,
			Self::Cond => &DEFAULT_TRAITS,
			Self::Constructor => &FUNCTION_TRAITS,
			Self::Contract => &DEFAULT_TRAITS,
			Self::Copy => &GROUP_TRAITS,
			Self::Custom => &DEFAULT_TRAITS,
			Self::Declarations => &GROUP_TRAITS,
			Self::Decl => &DEFAULT_TRAITS,
			Self::DefaultExport => &DEFAULT_TRAITS,
			Self::Define => &DEFAULT_TRAITS,
			Self::Directive => &DEFAULT_TRAITS,
			Self::Either => &DEFAULT_TRAITS,
			Self::Elif => &DEFAULT_TRAITS,
			Self::Else => &DEFAULT_TRAITS,
			Self::Enum => &ADDRESSABLE_CONTAINER_TRAITS,
			Self::Env => &DEFAULT_TRAITS,
			Self::Error => &DEFAULT_TRAITS,
			Self::Except => &DEFAULT_TRAITS,
			Self::Exports => &GROUP_TRAITS,
			Self::Expose => &DEFAULT_TRAITS,
			Self::Expression => &DEFAULT_TRAITS,
			Self::Field => &PACKED_LEAF_TRAITS,
			Self::Fields => &GROUP_TRAITS,
			Self::File => &DEFAULT_TRAITS,
			Self::Frame => &DEFAULT_TRAITS,
			Self::Function => &FUNCTION_TRAITS,
			Self::For => &DEFAULT_TRAITS,
			Self::ForIn => &DEFAULT_TRAITS,
			Self::ForOf => &DEFAULT_TRAITS,
			Self::Form => &DEFAULT_TRAITS,
			Self::Frontmatter => &DEFAULT_TRAITS,
			Self::Group => &DEFAULT_TRAITS,
			Self::GroupBy => &DEFAULT_TRAITS,
			Self::Headers => &GROUP_TRAITS,
			Self::Healthcheck => &DEFAULT_TRAITS,
			Self::Html => &GROUP_TRAITS,
			Self::Hunks => &GROUP_TRAITS,
			Self::Hunk => &DEFAULT_TRAITS,
			Self::If => &DEFAULT_TRAITS,
			Self::Iface => &PRESERVE_CHILDREN_TRAITS,
			Self::Impl => &CONTAINER_TRAITS,
			Self::Imports => &IMPORTS_TRAITS,
			Self::Includes => &GROUP_TRAITS,
			Self::InlineFragment => &DEFAULT_TRAITS,
			Self::Install => &DEFAULT_TRAITS,
			Self::Interface => &PRESERVE_CHILDREN_TRAITS,
			Self::Interpolation => &GROUP_TRAITS,
			Self::Item => &DEFAULT_TRAITS,
			Self::Join => &DEFAULT_TRAITS,
			Self::Key => &PACKED_LEAF_TRAITS,
			Self::KeyScripts => &DEFAULT_TRAITS,
			Self::Label => &DEFAULT_TRAITS,
			Self::Let => &DEFAULT_TRAITS,
			Self::List => &DEFAULT_TRAITS,
			Self::Loop => &DEFAULT_TRAITS,
			Self::Macro => &DEFAULT_TRAITS,
			Self::Map => &DEFAULT_TRAITS,
			Self::Markdown => &DEFAULT_TRAITS,
			Self::Match => &DEFAULT_TRAITS,
			Self::Method => &DEFAULT_TRAITS,
			Self::Methods => &GROUP_TRAITS,
			Self::Module => &CONTAINER_TRAITS,
			Self::Mustache => &DEFAULT_TRAITS,
			Self::Object => &DEFAULT_TRAITS,
			Self::Operation => &DEFAULT_TRAITS,
			Self::Operator => &DEFAULT_TRAITS,
			Self::Option => &DEFAULT_TRAITS,
			Self::Options => &GROUP_TRAITS,
			Self::OrderBy => &DEFAULT_TRAITS,
			Self::Parameters => &GROUP_TRAITS,
			Self::Preamble => &DEFAULT_TRAITS,
			Self::Proc => &CONTAINER_TRAITS,
			Self::Process => &CONTAINER_TRAITS,
			Self::Project => &DEFAULT_TRAITS,
			Self::Proto => &DEFAULT_TRAITS,
			Self::Py => &DEFAULT_TRAITS,
			Self::Python => &DEFAULT_TRAITS,
			Self::Query => &DEFAULT_TRAITS,
			Self::Receive => &DEFAULT_TRAITS,
			Self::Recipe => &DEFAULT_TRAITS,
			Self::Relations => &DEFAULT_TRAITS,
			Self::Render => &DEFAULT_TRAITS,
			Self::Return => &DEFAULT_TRAITS,
			Self::Root => &DEFAULT_TRAITS,
			Self::Rule => &DEFAULT_TRAITS,
			Self::Schema => &DEFAULT_TRAITS,
			Self::Script => &DEFAULT_TRAITS,
			Self::ScriptModule => &DEFAULT_TRAITS,
			Self::ScriptSetup => &DEFAULT_TRAITS,
			Self::Section => &DEFAULT_TRAITS,
			Self::Select => &DEFAULT_TRAITS,
			Self::Setting => &DEFAULT_TRAITS,
			Self::Shebang => &DEFAULT_TRAITS,
			Self::Shell => &DEFAULT_TRAITS,
			Self::Slot => &DEFAULT_TRAITS,
			Self::Snippet => &DEFAULT_TRAITS,
			Self::Source => &DEFAULT_TRAITS,
			Self::Stage => &DEFAULT_TRAITS,
			Self::StaticInit => &DEFAULT_TRAITS,
			Self::Statements => &GROUP_TRAITS,
			Self::Struct => &ADDRESSABLE_CONTAINER_TRAITS,
			Self::Style => &DEFAULT_TRAITS,
			Self::StyleScoped => &DEFAULT_TRAITS,
			Self::Switch => &DEFAULT_TRAITS,
			Self::Table => &DEFAULT_TRAITS,
			Self::Tag => &DEFAULT_TRAITS,
			Self::Target => &DEFAULT_TRAITS,
			Self::Template => &DEFAULT_TRAITS,
			Self::Text => &GROUP_TRAITS,
			Self::Trait => &PRESERVE_CHILDREN_TRAITS,
			Self::Translation => &DEFAULT_TRAITS,
			Self::Try => &DEFAULT_TRAITS,
			Self::Ts => &DEFAULT_TRAITS,
			Self::Type => &ADDRESSABLE_CONTAINER_TRAITS,
			Self::Typescript => &DEFAULT_TRAITS,
			Self::Union => &DEFAULT_TRAITS,
			Self::User => &DEFAULT_TRAITS,
			Self::Val => &DEFAULT_TRAITS,
			Self::Variable => &VARIABLE_TRAITS,
			Self::Variant => &PACKED_LEAF_TRAITS,
			Self::Variants => &DEFAULT_TRAITS,
			Self::VersionGate => &DEFAULT_TRAITS,
			Self::When => &DEFAULT_TRAITS,
			Self::Where => &DEFAULT_TRAITS,
			Self::While => &DEFAULT_TRAITS,
			Self::With => &GROUP_TRAITS,
			Self::Workdir => &DEFAULT_TRAITS,
			Self::Conflict => &DEFAULT_TRAITS,
			Self::Ours => &PACKED_LEAF_TRAITS,
			Self::Theirs => &PACKED_LEAF_TRAITS,
			Self::Chunk => &DEFAULT_TRAITS,
		}
	}

	pub fn path_segment(self, identifier: Option<&str>) -> String {
		match identifier {
			Some(identifier) => format!("{}_{identifier}", self.prefix()),
			None => self.prefix().to_string(),
		}
	}

	pub fn from_sanitized_kind(kind: &str) -> Self {
		match kind {
			"add" => Self::Add,
			"after" => Self::After,
			"alias" => Self::Alias,
			"algo" => Self::Algo,
			"arg" => Self::Arg,
			"argv" => Self::Argv,
			"array" => Self::Array,
			"at" => Self::At,
			"attr" => Self::Attr,
			"attr_expr" => Self::AttrExpr,
			"attrs" => Self::Attrs,
			"block" => Self::Block,
			"block_if" => Self::BlockIf,
			"block_locals" => Self::BlockLocals,
			"body" => Self::Body,
			"case" => Self::Case,
			"cases" => Self::Cases,
			"catch" => Self::Catch,
			"cell" => Self::Cell,
			"class" => Self::Class,
			"clause" => Self::Clause,
			"cmd" => Self::Cmd,
			"code" => Self::Code,
			"cond" => Self::Cond,
			"constructor" => Self::Constructor,
			"contract" => Self::Contract,
			"copy" => Self::Copy,
			"custom" => Self::Custom,
			"decls" | "declarations" => Self::Declarations,
			"decl" => Self::Decl,
			"default_export" => Self::DefaultExport,
			"define" => Self::Define,
			"directive" => Self::Directive,
			"either" => Self::Either,
			"elif" => Self::Elif,
			"else" => Self::Else,
			"enum" => Self::Enum,
			"env" => Self::Env,
			"error" => Self::Error,
			"except" => Self::Except,
			"exports" => Self::Exports,
			"expose" => Self::Expose,
			"expr" | "expression" => Self::Expression,
			"field" => Self::Field,
			"fields" => Self::Fields,
			"file" => Self::File,
			"frame" => Self::Frame,
			"fn" | "function" => Self::Function,
			"for" => Self::For,
			"for_in" => Self::ForIn,
			"for_of" => Self::ForOf,
			"form" => Self::Form,
			"frontmatter" => Self::Frontmatter,
			"group" => Self::Group,
			"group_by" => Self::GroupBy,
			"headers" => Self::Headers,
			"healthcheck" => Self::Healthcheck,
			"html" => Self::Html,
			"hunks" => Self::Hunks,
			"hunk" => Self::Hunk,
			"if" => Self::If,
			"iface" => Self::Iface,
			"impl" => Self::Impl,
			"imports" => Self::Imports,
			"includes" => Self::Includes,
			"inline_fragment" => Self::InlineFragment,
			"install" => Self::Install,
			"interface" => Self::Interface,
			"interpolation" => Self::Interpolation,
			"item" => Self::Item,
			"join" => Self::Join,
			"key" => Self::Key,
			"key_scripts" => Self::KeyScripts,
			"label" => Self::Label,
			"let" => Self::Let,
			"list" => Self::List,
			"loop" => Self::Loop,
			"macro" => Self::Macro,
			"map" => Self::Map,
			"markdown" => Self::Markdown,
			"match" => Self::Match,
			"meth" | "method" => Self::Method,
			"methods" => Self::Methods,
			"mod" | "module" => Self::Module,
			"mustache" => Self::Mustache,
			"object" => Self::Object,
			"operation" => Self::Operation,
			"operator" => Self::Operator,
			"option" => Self::Option,
			"options" => Self::Options,
			"order_by" => Self::OrderBy,
			"params" | "parameters" => Self::Parameters,
			"preamble" => Self::Preamble,
			"proc" => Self::Proc,
			"process" => Self::Process,
			"project" => Self::Project,
			"proto" => Self::Proto,
			"py" => Self::Py,
			"python" => Self::Python,
			"query" => Self::Query,
			"receive" => Self::Receive,
			"recipe" => Self::Recipe,
			"relations" => Self::Relations,
			"render" => Self::Render,
			"ret" | "return" => Self::Return,
			"root" => Self::Root,
			"rule" => Self::Rule,
			"schema" => Self::Schema,
			"script" => Self::Script,
			"script_module" => Self::ScriptModule,
			"script_setup" => Self::ScriptSetup,
			"section" => Self::Section,
			"select" => Self::Select,
			"setting" => Self::Setting,
			"shebang" => Self::Shebang,
			"shell" => Self::Shell,
			"slot" => Self::Slot,
			"snippet" => Self::Snippet,
			"source" => Self::Source,
			"stage" => Self::Stage,
			"static_init" => Self::StaticInit,
			"stmts" | "statements" => Self::Statements,
			"struct" => Self::Struct,
			"style" => Self::Style,
			"style_scoped" => Self::StyleScoped,
			"switch" => Self::Switch,
			"table" => Self::Table,
			"tag" => Self::Tag,
			"target" => Self::Target,
			"template" => Self::Template,
			"text" => Self::Text,
			"trait" => Self::Trait,
			"translation" => Self::Translation,
			"try" => Self::Try,
			"ts" => Self::Ts,
			"type" => Self::Type,
			"typescript" => Self::Typescript,
			"union" => Self::Union,
			"user" => Self::User,
			"val" => Self::Val,
			"var" | "variable" => Self::Variable,
			"variant" => Self::Variant,
			"variants" => Self::Variants,
			"version_gate" => Self::VersionGate,
			"when" => Self::When,
			"where" => Self::Where,
			"while" => Self::While,
			"with" => Self::With,
			"workdir" => Self::Workdir,
			"conflict" => Self::Conflict,
			"ours" => Self::Ours,
			"theirs" => Self::Theirs,
			"chunk" => Self::Chunk,
			_ => Self::Chunk,
		}
	}
}
